### ISSUE TITLE
Terminating error

### ISSUE THREAD

**Issue by thunder-19** [RudimentalHack/RudiNuker#2]
When you try terminate your account it's give you a 401 error.

**Comment by RudimentalHack** [comment]
Will look into this issue later and see what's causing the issue.
Can you please describe what you did to achieve this error.
Step by Step process if possible thank you.

**Comment by thunder-19** [comment]
When you do the terminated option, you enter your token and press enter its split out a error 401 and doesn't banned the account.

**Comment by RudimentalHack** [comment]
I think the issue has been resolved refer to https://github.com/RudimentalHack/RudiNuker/commit/4c41ef25acbb38cd97733b4a3ac822800da2d17e

**Comment by RudimentalHack** [comment]
It's been 12 days since this issue was opened, if you have any further issues please make a new issue.
I am going to mark this as resolved.
